== 4.0.3

[[enh-403]]
=== Enhancements

* Added the declarative configuration support for the client load balancer.
https://github.com/hazelcast/hazelcast/pull/17482[#17482]
* Added public classes to expose the member and client side caching
provider implementations without referring to internal classes.
https://github.com/hazelcast/hazelcast/pull/17421[#17421]
* Updated the Hazelcast Kubernetes dependency to 2.0.2.
https://github.com/hazelcast/hazelcast/pull/17255[#17255]
* Added the ability to set the expiration times for entries when
using entry processors.
https://github.com/hazelcast/hazelcast/pull/17175[#17175]

[[fixes-403]]
=== Fixes

* Fixed `NullPointerException` when using IMap with `HASH` indexes.
https://github.com/hazelcast/hazelcast/pull/17527[#17527]
* Fixed the rendering of diagnostics in case there is an exception inside a diagnostics plugin.
https://github.com/hazelcast/hazelcast/pull/17502[#17502]
* Increased the dependency versions for Jackson and SnakeYAML to mitigate the security vulnerabilities.
https://github.com/hazelcast/hazelcast/pull/17510[#17510]
* Fixed the propagation of exception from a function registered on a not-yet completed `CompletionStage`.
https://github.com/hazelcast/hazelcast/pull/17520[#17520]
* Fixed a race condition when overwriting `CacheManager` during JCache creation.
https://github.com/hazelcast/hazelcast/pull/17292[#17292]
* Fixed the `NATIVE` memory leak when using `IMap.executeOnKeys()` from an IMDG client.
https://github.com/hazelcast/hazelcast/pull/17274[#17274]
* Resolved a performance issue when using `PagingPredicate` in combination with JDK8.
https://github.com/hazelcast/hazelcast/pull/17211[#17211]
* Fixed the client behavior when cluster encounters a split-brain.
In some cases, the client was unable to reconnect to the cluster, even after the cluster is healed.
https://github.com/hazelcast/hazelcast/pull/17148[#17148]
* Improved disposing of off-heap memory when metrics are being used.
https://github.com/hazelcast/hazelcast/pull/17145[#17145]