== 4.1.2

[[fixes-412]]
=== Fixes

* Fixed an issue where the Java client was not receiving membership events
when a member with Hot Restart Persistence is restarted.
https://github.com/hazelcast/hazelcast/pull/18268[#18268]
* Fixed an issue where the Near Cache configuration of a map in client
was not the same after the client is recreated with the
same client failover configuration.
https://github.com/hazelcast/hazelcast/pull/18356[#18356]
* Fixed an issue that prohibited Hazelcast from being used as Tomcat session manager
when it is also deployed in a web application context:
When a client application that uses Hazelcast tries to connect to the Hazelcast cluster and this
application's web sessions are persisted using Hazelcast's Tomcat session manager,
the session manager could not connect to the cluster. This has been
fixed by improving Hazelcast's service loader mechanism.
https://github.com/hazelcast/hazelcast/pull/18116[#18116]
* Fixed an issue where the metrics for map hits statistics in Management Center
were decreasing as the map entries are being expired.
https://github.com/hazelcast/hazelcast/pull/18112[#18112]
* When the in-memory format of a map is `NATIVE` and the uploaded user code
has missing classes (in case the user code deployment feature is used),
the resulting exception could not be seen on the client side when a map query is run.
This was causing the client to hang indefinitely and fixed by improving the
failure handling for this case.
https://github.com/hazelcast/hazelcast/pull/18084[#18084]
* Fixed an issue where the queue items were being delivered more
than once when they are reproduced after a member leaves the cluster.
https://github.com/hazelcast/hazelcast/issues/18057[#18057]
* When the user code deployment is used and the classes to be deployed
have `com.hazelcast` prefix, it was causing failures in other Hazelcast
products, e.g., Jet. This has been fixed by making use of the context classloader
when loading such classes.
https://github.com/hazelcast/hazelcast/pull/17915[#17915]
* The `-c` parameter of the `cp-subsystem.sh` script
was used for both cluster name and group variables. This has
been fixed by introducing the `-g` parameter for groups.
https://github.com/hazelcast/hazelcast/pull/17907[#17907]
* Fixed an issue where the `remove()` and `delete()` operations
of maps were not updating the local map statistics.
https://github.com/hazelcast/hazelcast/issues/17750[#17750]


