== 4.1.3

[[enh-413]]
=== Enhancements

* Introduced a thread local queue with fixed size to perform the sampling of keys
so that the uncontrolled growth of this queue is prevented.
https://github.com/hazelcast/hazelcast/pull/18480[#18480]
* Updated the version of `hazelcast-kubernetes` dependency to 2.2.2.
https://github.com/hazelcast/hazelcast/pull/18331[#18331]
* Added the ability to register the class definition of the parent generic record and check the class definition compatibility for nested portable fields.
https://github.com/hazelcast/hazelcast/pull/18284[#18284]

[[fixes-413]]
=== Fixes

* The difference between the Near Cache configurations before and after
a client is recreated with the same client failover configuration is
fixed now.
https://github.com/hazelcast/hazelcast/pull/18361[#18361]
* The eviction of the idle entries is now stable in IMDG 4.x series
by aligning the behaviors of index-scan and full-scan in maps.
https://github.com/hazelcast/hazelcast/pull/18346[#18346]
* The `IllegalArgumentException` is not thrown anymore when there is Near Cache
configured for both the member and client sides for the same map and
`serialize-keys` option is `false`.
https://github.com/hazelcast/hazelcast/pull/18313[#18313]
