== 4.1

[[nf-41]]
=== New Features

*_Hazelcast IMDG Open Source New Features:_*

* **SQL Implementation:** Implemented the SQL engine that
supports map scans, index scans, projections and filters.
It also introduces the `hazelcast-sql` module to handle the
SQL engine's dependencies on Apache Calcite.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#sql[SQL section^].
* **Automatic Discovery Strategy Detection:** Hazelcast now automatically detects
the cloud environment it's running on (Kubernetes, AWS, GCP or Azure) and applies
the necessary discovery strategy for the environment. This allows automatically
forming the Hazelcast clusters in cloud environments without any configuration.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#auto-detection[Auto Detection section^].
* **Overriding Configuration:** You can now override the configuration entries
of your cluster without changing the declarative configuration files (XML/YAML).
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#overriding-configuration[Overriding Configuration section^].
* **Instance Tracking:** Hazelcast now writes a file on a Hazelcast member startup
at the configured location. This file contains metadata about the member such as version, product name
and process ID, and it is not deleted on the member shutdown.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#instance-tracking[Instance Tracking section^].

*_Hazelcast IMDG Enterprise New Features:_*

* **Security Audit Logging:** This feature allows observing some important cluster events.
Auditable events have a unique type ID, and contain a timestamp and importance level.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#auditlog[Logging Auditable Events section^].

[[enh-41]]
=== Enhancements

*_Hazelcast IMDG Open Source Enhancements:_*

* **Improvements in Partial Network Disconnections:** Introduced properties
to be configured to detect and resolve the partial network issues among the
Hazelcast IMDG members.
See link:https://github.com/hazelcast/hazelcast/pull/16680[#16680^] and the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#partial-network-partitions[Partial Network Partitions section^].
* **Parallel Independent Migrations:** Parallelized the partition replica migrations so that
the time needed for rebalancing the partitions after adding
or removing a member to/from a cluster is reduced. See the `hazelcast.partition.max.parallel.migrations` property explanation in the
link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#system-properties[System Properties appendix^].
* **CP Subsystem Listeners and Metrics:** Added membership and group availability
listeners for CP Subsystem. Also, added support for publishing CP Subsystem and CP data structure
statistics via Metrics.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#cp-subsystem-listeners[CP Subsystem Listeners section^].
* **GenericRecord:** Added support for accessing domain objects without domain classes.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#accessing-domain-objects-without-domain-classes[GenericRecord section^].
* **Thread Affinity:** Introduced the CPU thread affinity; threads can have affinity for particular CPUs and using this you have a better control on the latency and a better throughput.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#cpu-thread-affinity[CPU Thread Affinity section^].
* **Trusted Interfaces:** It is now possible to restrict the source IP addresses
from which the Management Center operations are allowed.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#limiting-source-addresses[Limiting Source Addresses section^].
* **Priority Queue:** Added support for the queues with comparators. Using Priority
Queue, you can define items with higher priority to be polled first.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#priority-queue[Priority Queue section^].
* **Statistics for Durable and Scheduled Executor Services:** Added the statistics for scheduled and durable executor services, and for the executor of offloaded entry
processors to be monitored by Management Center.

*_Hazelcast IMDG Enterprise Enhancements:_*

* **Out-of-the-Box Kerberos Support:** Introduced support for Kerberos
authentication protocol which is one of the standard
solutions for single-sign-on. It also adds the GSSAPI authentication support in
LDAP configuration.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#kerberos-authentication-type[Kerberos Authentication Type section^].
* **Multiple Persistent Directories:** Added support for multiple mounting
directories in the persistent memory configuration and also thread affinity for NVMs
(Non-Volatile Main Memories).
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#using-persistent-memory[Using Persistent Memory section^].
* **WAN Throttling Mechanism**: This prevents the WAN consumers from 
getting overloaded by the WAN producers if transferring the WAN events takes
less time than processing them in the target cluster. This can be the case with
WAN synchronization if the network latency is low enough. It can be configured using
the following properties:
** `hazelcast.wan.consumer.invocation.threshold`
** `hazelcast.wan.consumer.ack.delay.backoff.init`
** `hazelcast.wan.consumer.ack.delay.backoff.max`
** `hazelcast.wan.consumer.ack.delay.backoff.multiplier`
+
https://github.com/hazelcast/hazelcast/pull/17113[#17113]
* Implemented a new concurrent High-Density Memory Store index
for the queries, based on B+ tree that is enabled by default;
brings better performance for lookup queries and enables SQL queries.

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Added the missing `replicatedmap-permission` support to the
XML and YAML configuration handlers.
https://github.com/hazelcast/hazelcast/pull/17812[#17812]
* Replaced the word "should" with "must" in the exception messages
to improve the user focus and indicate obligation rather than advice.
https://github.com/hazelcast/hazelcast/pull/17710[#17710]
* Added the `getAndDecrement()` operation support for the `IAtomicLong`
data structure.
https://github.com/hazelcast/hazelcast/pull/17699[#17699]
* Introduced the `mode` configuration attribute for the
persistent memory. It defines operational mode of it which can be
either `MOUNTED` or SYSTEM_MEMORY.
https://github.com/hazelcast/hazelcast/pull/17696[#17696]
* Added the support for checking duplicate fields when building
class definitions.
https://github.com/hazelcast/hazelcast/pull/17682[#17682]
* Added the support for IList with nullable items to the client protocol.
https://github.com/hazelcast/hazelcast/pull/17690[#17690]
* Improved the robustness of the diagnostics log writer and its plugins.
https://github.com/hazelcast/hazelcast/pull/17665[#17665]
* Added the client name tag to the client related metrics.
https://github.com/hazelcast/hazelcast/pull/17654[#17654]
* Added a check for IMap `READ` permissions for the maps involved in the
SQL query executions.
https://github.com/hazelcast/hazelcast/pull/17612[#17612]
* Added the support for accessing the Hazelcast instance in the
login modules and credential factories.
https://github.com/hazelcast/hazelcast/pull/17605[#17605]
* Introduced a simplified configuration of Kerberos authentication
for simple scenarios.
https://github.com/hazelcast/hazelcast/pull/17573[#17573]
* Added statistics support for IBM, OpenJ9, ZGC and Shenandoah.
https://github.com/hazelcast/hazelcast/pull/17561[#17561]
* Introduced a state-tracking mechanism for the external configuration
parser; all mismatched/unapplied configuration entries coming from
environment variables or system properties are now logged.
https://github.com/hazelcast/hazelcast/pull/17559[#17559]
* Updated the `jackson.version` to 2.11.2 and
`SnakeYAML` to 2.1.
https://github.com/hazelcast/hazelcast/pull/17484[#17484],
https://github.com/hazelcast/hazelcast/pull/17446[#17446]
* Added support for the merge operation in IMap.
https://github.com/hazelcast/hazelcast/pull/17419[#17419]
* Added public classes to expose the member- and
client-side caching provider implementations (in the JCache implementation)
without referring to internal classes.
https://github.com/hazelcast/hazelcast/pull/17320[#17320]
* Improved the entry processing mechanism so that the read-only processors on backups
are not executed anymore.
https://github.com/hazelcast/hazelcast/pull/17318[#17318]
* Improved `CacheSimpleConfig` so that it now accepts cache name in its constructors.
https://github.com/hazelcast/hazelcast/issues/17287[#17287]
* Cleaned up the noisy initial log messages on Hazelcast startups.
https://github.com/hazelcast/hazelcast/pull/17243[#17243]
* Introduced auto-disposable tasks for the scheduled executor service.
https://github.com/hazelcast/hazelcast/pull/17215[#17215]
* Added client labels to `ClientEndpointImpl.toString()`
to simplify the client identification (in addition to client uuid)
on the Hazelcast member side.
https://github.com/hazelcast/hazelcast/issues/17178[#17178]
* Added exception handling when creating caches with tenant control.
https://github.com/hazelcast/hazelcast/pull/17122[#17122]
* Added support for `IMap.compute()`.
https://github.com/hazelcast/hazelcast/pull/17030[#17030]
* Added support to allow submitting and executing operations while a member
is shutting down to increase the availability of a cluster more that keeps
large data.
https://github.com/hazelcast/hazelcast/pull/17028[#17028]
* Added `ExtendedMapEntry` in order to create a mechanism for setting TTLs in
entry processors.
https://github.com/hazelcast/hazelcast/pull/16991[#16991]
* Added `hazelcast-azure` discovery plugin to the `hazelcast-all` module.
https://github.com/hazelcast/hazelcast/pull/16982[#16982]
* Introduced the `ConfigRecognition` API that determines if a
provided declarative configuration is recognized by the rules defined in a given
implementation. Along with the API the following three implementations are added:
** `MemberConfigRecognizer` for recognizing member XML and YAML configurations
** `ClientConfigRecognizer` for recognizing client XML and YAML configurations
** `ClientFailoverConfigRecognizer` for recognizing failover client XML and YAML configurations
+
https://github.com/hazelcast/hazelcast/pull/16958[#16958]
* Added the `publishAll()`, `publishAllAsync()` and `publishAsync()`
methods to ITopic.
https://github.com/hazelcast/hazelcast/pull/16946[#16946]
* Made the diagnostics logs cloud-friendly so that they
can also be sent to `stdout` in addition to sending to local files.
https://github.com/hazelcast/hazelcast/pull/16941[#16941]
* Improved the mechanism of partition table updates to
eliminate the latencies when these updates are sent to the clients by a member.
https://github.com/hazelcast/hazelcast/pull/16939[#16939]
* Improved the client configuration such that when the client
failover configuration is provided, the reconnect mode cannot
be set as `off`; it now fails fast in this case.
https://github.com/hazelcast/hazelcast/pull/16886[#16886]
* Introduced the `forEach()` loop support for IMap.
https://github.com/hazelcast/hazelcast/pull/16877[#16877]
* Added the `load()` method to `Config`, `ClientConfig` and
`ClientFailoverConfig` classes. This method loads the configuration
with the known locations. If not found, the default configuration is returned.
https://github.com/hazelcast/hazelcast/pull/16864[#16864]
* Improved the `deleteAll()` (MapStore) and ITopic Javadocs.
https://github.com/hazelcast/hazelcast/pull/16862[#16862],
https://github.com/hazelcast/hazelcast/pull/16861[#16861],
* Added support for `IMap.computeIfAbsent()`.
https://github.com/hazelcast/hazelcast/pull/16808[#16808]
* Added the `setAll()` and `setAllAsync()` methods for IMap.
https://github.com/hazelcast/hazelcast/pull/16787[#16787]
* Added the creation time metric for the executor service.
https://github.com/hazelcast/hazelcast/pull/16775[#16775]
* Improved an unclear exception message for credentials.
https://github.com/hazelcast/hazelcast/pull/16756[#16756]
* Updated the related aspects of Hazelcast IMDG after the
changes done on the client protocol side to add the ability
to add new parameters, methods, services, events and custom types
to codecs.
https://github.com/hazelcast/hazelcast/pull/16718[#16718]
* Introduced the `putAllAsync()` method for MultiMap.
https://github.com/hazelcast/hazelcast/pull/16698[#16698]
* Defined metrics for ISet and IList collections.
https://github.com/hazelcast/hazelcast/pull/16665[#16665]
* Upgraded log4j2 version to 2.13.0.
https://github.com/hazelcast/hazelcast/pull/16654[#16654]
* Improved the `computeIfPresent()` implementation so that now it keeps a
clone of the old/existing value and uses that for replace/delete operations.
https://github.com/hazelcast/hazelcast/pull/16636[#16636]
* Introduced the `hazelcast.logging.details.enabled` property
to make the logging of cluster version, name and IP optional to
decrease the noise in the logs when, for example, you have a single-member cluster.
https://github.com/hazelcast/hazelcast/pull/16622[#16622]
* Upgraded the Hazelcast Kubernetes plugin version to 2.0.1.
https://github.com/hazelcast/hazelcast/pull/16590[#16590]
* Added the support for automatically detecting the classloader
of a type for the user code deployment feature.
https://github.com/hazelcast/hazelcast/pull/16585[#16585]
* Made `IMap.putAllAsync()` and `IMap.submitToKeys()` methods public API.
https://github.com/hazelcast/hazelcast/issues/16449[#16449]
* Clarified the exception message when you connect to a cluster with an
invalid cluster name.
https://github.com/hazelcast/hazelcast/issues/15099[#15099]
* Refactored the check and retry initialization logic of
`ReplicatedMapProxy` so that they are performed in parallel for different
partitions.
https://github.com/hazelcast/hazelcast/pull/14331[#14331]
* Added a test for the `ClientConsoleApp` class. 
https://github.com/hazelcast/hazelcast/issues/12298[#12298]
* Improved the behavior of `ConcurrentMap.computeIfPresent`:
combined single client-server round trips instead of two (for `get` and
`replace` methods).
https://github.com/hazelcast/hazelcast/issues/11958[#11958]

[[bc-41]]
=== Breaking Changes

* Starting a standalone Hazelcast instance requires disabling Auto Detection joiner
(before it required disabling Multicast joiner).
https://github.com/hazelcast/hazelcast/pull/17112[#17112]
* In a CP subsystem session, a generic `IllegalStateException` was being thrown when Hazelcast
is shutdown. Now the same situation throws `HazelcastInstanceNotActiveException`.
https://github.com/hazelcast/hazelcast/issues/17120[#17120]
* Implemented and/or overridden the default methods in Java 8 collections,
such as `computeIfAbsent()`, `forEach()` `compute()` and `replaceAll()` for maps.
https://github.com/hazelcast/hazelcast/issues/14913[#14913]

[[fixes-41]]
=== Fixes

* Fixed an exception in the `/node-state` REST calls when the member
is not fully activated.
https://github.com/hazelcast/hazelcast/pull/17798[#17798]
* Fixed an issue where Hazelcast was not releasing the acquired lock
sessions that fail for the reasons other than session expiration and
wait key cancellation.
https://github.com/hazelcast/hazelcast/pull/17697[#17697]
* Fixed an issue where Hazelcast was returning `false` if a client
is successfully deregistered from any member, but events are still
delivered for the non-deregistered ones.
https://github.com/hazelcast/hazelcast/pull/17646[#17646]
* Fixed a data loss issue that was happening while promoting a lite member
to a data member.
https://github.com/hazelcast/hazelcast/issues/17621[#17621]
* Fixed an issue where the configuration was not updating entries' time-to-live
values if the entry processor implements the `Offloadable` interface.
https://github.com/hazelcast/hazelcast/issues/17606[#17606]
* Fixed an issue where the caller stacktrace was missing on the
rethrown async runtime exceptions.
https://github.com/hazelcast/hazelcast/pull/17546[#17546]
* Fixed the rendering of diagnostics in case there is an exception
inside a diagnostics plugin.
https://github.com/hazelcast/hazelcast/pull/17501[#17501]
* Fixed an exception that is thrown when using the entry store API and issuing
a `put` into the IMap for an item which is not in the map but
exists in the backing store.
https://github.com/hazelcast/hazelcast/issues/17441[#17441]
* Fixed an issue where the custom load balancers
could not be configured declaratively.
https://github.com/hazelcast/hazelcast/pull/17415[#17415]
* Fixed a race issue when creating a cache (JCache) using
multiple methods with the same cache name but having different keys.
https://github.com/hazelcast/hazelcast/pull/17286[#17286]
* Fixed an issue where the repeated calls of `executeOnKeys()`
in Hazelcast clients for `NATIVE` maps was causing a continuous
increase in the used memory and exhaustion of the memory pool after a while.
https://github.com/hazelcast/hazelcast/pull/17276[#17276]
* Fixed an issue where `ReliableTopicMessageListener` was firing
a warning when the client is shutting down.
https://github.com/hazelcast/hazelcast/pull/17153[#17153]
* Fixed an issue where the client was stuck with an outdated
member list after a split-brain scenario.
https://github.com/hazelcast/hazelcast/pull/17147[#17147]
* Fixed the member side user code deployment; it was throwing an exception
when inner classes are used to be loaded.
https://github.com/hazelcast/hazelcast/issues/17044[#17044]
* Fixed the broken interoperability between the `CompletableFuture` methods.
https://github.com/hazelcast/hazelcast/pull/17020[#17020]
* Fixed an issue where touching a map entry having an entry processor working on it
was modifying its time-to-live.
https://github.com/hazelcast/hazelcast/issues/16987[#16987]
* Fixed an issue in the cache service where its pre-join
operation was considering `CacheConfig` as resolved: it
was assuming that key/value types, user customizations and
other cache configurations have been loaded. This was an issue
when the cache is not touched yet.
https://github.com/hazelcast/hazelcast/pull/16917[#16917]
* Fixed an issue where Management Center was not working as expected
when the cluster is set up using advanced network configuration.
https://github.com/hazelcast/hazelcast/pull/16910[#16910]
* Fixed an issue where `ServiceLoader` was round-tripping between URL and URI,
and consequently loses the associated `URLStreamHandler` when trying to load
Hazelcast from a custom class loader.
https://github.com/hazelcast/hazelcast/issues/16846[#16846]
* Fixed an issue where the class definitions, that are registered explicitly in
the serialization configuration and have the same class ID in different factories,
were not handled properly.
https://github.com/hazelcast/hazelcast/pull/16831[#16831]
* Fixed the `NullPointerException` in `IndexCopyBehavior.NEVER` mode.
https://github.com/hazelcast/hazelcast/pull/16784[#16784]
* Fixed an issue where the client XML configuration could not
properly handle the empty Near Cache name.
https://github.com/hazelcast/hazelcast/issues/16768[#16768]
* Fixed an issue where the client permissions for Reliable Topic and Ringbuffer
were missing.
https://github.com/hazelcast/hazelcast/pull/16755[#16755]
* Fixed an issue where the type information was missing the Metrics MBeans.
https://github.com/hazelcast/hazelcast/pull/16747[#16747]
* Fixed an issue where the REST API was always requiring the call URLs
to end with a slash character.
https://github.com/hazelcast/hazelcast/pull/16688[#16688]
* Fixed an issue where the service URL for Eureka could not be set
using the declarative configuration.
https://github.com/hazelcast/hazelcast/pull/16679[#16679]
* Fixed an issue where the wait key of a blocking call within
a Raft invocation was still being reported as a live operation,
when the key times out.
https://github.com/hazelcast/hazelcast/pull/16614[#16614]
* Fixed an issue where the upload of classes using the client
user code deployment were not successful when they are retrieved not
in their created order.
https://github.com/hazelcast/hazelcast/pull/16612[#16612]
* Fixed an issue where the size() method was returning a negative
value when map, cache and multimap contain more than Integer.MAX_VALUE entries.
https://github.com/hazelcast/hazelcast/pull/16594[#16594]
* Fixed an invalidation issue when using a transactional map
from a cache with a Near Cache: the cache invalidation event occurs
when the `transactionalMap.put` method is called. As a result,
the entry was getting invalidated before the change is committed to the map.
https://github.com/hazelcast/hazelcast/pull/16579[#16579]
* Fixed an issue where `InPredicate` was not invoking value comparison when the
read attribute is null.
https://github.com/hazelcast/hazelcast/issues/15100[#15100]
* Fixed an issue where Map, Cache, MultiMap data structures
were returning negative values (`size()`) when the size is more than
`Integer.MAX_VALUE`.
https://github.com/hazelcast/hazelcast/issues/14935[#14935]
* Fixed an issue when a Hazelcast client calls the distributed executor service
and the callable throws an exception with a custom type, then the exception
was not being transported to the client.
https://github.com/hazelcast/hazelcast/issues/9753[#9753]

[[contributors-41]]
===  Contributors

We would like to thank the contributors from our open source
community who worked on this release:

* https://github.com/inelpandzic[Inel Pandzic]
* https://github.com/omidp[Omid Pourhadi]
* https://github.com/ryanlindeborg[Ryan Lindeborg]
* https://github.com/santhoshkumarbs[Santhosh Kumar]
* https://github.com/KowalczykBartek[Bartek Kowalczyk]
* https://github.com/webashutosh[Ashutosh Agrawal]
* https://github.com/aberkecz[Ádám Berkecz]
* https://github.com/HugeOrangeDev[HugeOrangeDev]
* https://github.com/pertsodian[Harry Tran]
* https://github.com/StephenOTT[Stephen Russett]
* https://github.com/ulfjack[Ulf Adams]
* https://github.com/abdulazizali77[Abdul Aziz Ali]
* https://github.com/netudima[Dmitry Konstantinov]
* https://github.com/chanmol1999[Anmol Chaddha]
* https://github.com/lprimak[lprimak]
* https://github.com/keteracel[keteracel]
* https://github.com/buraksezer[Burak Sezer]
* https://github.com/wangumer[wangumer]
* https://github.com/the-thing[Marcin L]
* https://github.com/stefanbirkner[Stefan Birkner]
* https://github.com/andrewoelfing[André Wölfing]
* https://github.com/ndeevy[ndeevy]
