== 4.2.5

If you're using eviction/expiration for maps, you must set the `per-entry-stats-enabled` property to `true`. In previous versions of Hazelcast IMDG, some map entries were not always evicted or expired according to their time-to-live or maximum idle duration configurations.

[[enh-425]]
=== Enhancements

* Introduced a system property for allowing you to audit that all the Hazelcast instances running in your
environment have the instance tracking file name set correctly in the configuration. See the note in xref:management:instance-tracking.adoc[Instance Tracking].
https://github.com/hazelcast/hazelcast/pull/19929[#19929]
* Enabled XXE (XML External Entity Reference) protection for `XMLInputFactory`. The issue was reported through
https://huntr.dev/bounties/d63972a2-b910-480a-a86b-d1f75d24d563/.
https://github.com/hazelcast/hazelcast/pull/20942[#20942]
* The probe level for most of the network related statistics has been changed to "DEBUG" to decrease the pressure on Management Center; now they are not sent to Management Center by default. If you want to see these statistics, you need to set the "hazelcast.metrics.debug.enabled" property to `true`.
https://github.com/hazelcast/hazelcast/pull/21275[#21275]

[[fixes-425]]
=== Fixes

* Fixed an issue where the statistics like puts and removals were not increasing when these operations are executed through Transactional interface.
https://github.com/hazelcast/hazelcast/pull/21105[#21105]
* Fixed an issue where Hazelcast clients, which have only the IP address of a member to connect (but the member also has a hostname), were not able to connect to the cluster.
https://github.com/hazelcast/hazelcast/pull/20631[#20631]
* Hazelcast’s memcached implementation was interpreting the number values and parameters for `incr` and `decr` wrongly (numbers were being converted into byte arrays instead of decimals).
This has been fixed by making these commands' implementations strictly follow the memcached protocol specification.
https://github.com/hazelcast/hazelcast/pull/19676[#19676]
* Fixed an issue where the `totalPublishes` statistics for the Reliable Topic data structure were always generated as `0`.
https://github.com/hazelcast/hazelcast/pull/19656[#19656]
* Fixed an issue where the `map.clear()` and `cache.clear()` methods were evicting all entries in all near caches of all the maps in a cluster, not only the map on which these methods are called.
https://github.com/hazelcast/hazelcast/issues/19501[#19501]
* Fixed an issue that caused some map entries to remain in Hazelcast even when you configured eviction or expiration. https://github.com/hazelcast/hazelcast/pull/19483[#19483]

[[rdf-425]]
=== Removed/Deprecated Features

The following system properties have been deprecated:

* `hazelcast.client.statistics.enabled`
* `hazelcast.client.statistics.period.seconds`
