== 4.2

[[nf-42]]
=== New Features

*_Hazelcast IMDG Open Source New Features:_*

* **Sorting Support for Hazelcast SQL:** Added the support of SQL sorting feature. 
By using the newly implemented ORDER BY, LIMIT, and OFFSET constructions, 
you can see the query results being ordered in ascending or descending fashion, 
limit the count of results, or skip some results. See the
https://docs.hazelcast.com/imdg/4.2/sql/select-statement.html#sorting[documentation] for examples.
* **Node Aware Partition Grouping:** Added the support of
partition grouping mechanism in the Hazelcast discovery plugin for Kubernetes.
You can create partition groups according to the name of the node which is
provided by this plugin and on which the containers/pods run.
See the https://docs.hazelcast.com/imdg/4.2/clusters/partition-group-configuration.html#node-aware-partition-grouping[NODE_AWARE section]
of the IMDG Reference Manual for more information.
* **Placement Aware Partition Grouping:** Added the support of
partition grouping mechanism in the Hazelcast discovery plugin for AWS.
You can group members according to their placement metadata provided by the cloud providers,
such as rack, fault domain, power sources, network, and resources of a virtual machine in a zone.
See the https://docs.hazelcast.com/imdg/4.2/clusters/partition-group-configuration.html#placement-aware[PLACEMENT_AWARE section]
of the IMDG Reference Manual for more information.
* **Dynamic Log Level Support**: Added the support of changing Hazelcast log levels
without restarting cluster members.
See the https://docs.hazelcast.com/imdg/4.2/clusters/logging-configuration.html#dynamically-changing-log-levels[Dynamically Changing Log Levels section].

[[bc-42]]
=== Breaking Changes

* Improved the `GenericRecord` and serialization API:
** `GenericRecord#read()` and `GenericRecord.Builder#write()` methods have been renamed as
`get()`  and `set()`, respectively.
** `GenericRecord.Builder` has been moved to its own class as `GenericRecordBuilder`.
** `UTF` has been renamed as `String` for the following methods, which are now deprecated:
*** `ClassDefinitionBuilder.addUTFField()`
*** `ClassDefinitionBuilder.addUTFArrayField()`
*** `PortableWriter.writeUTF()`
*** `PortableWriter.writeUTFArray()`
*** `PortableReader.readUTF()`
*** `PortableReader.readUTFArray()`
*** `ObjectDataOutput.writeUTF()`
*** `ObjectDataOutput.writeUTFArray()`
*** `ObjectDataInput.readUTF()`
*** `ObjectDataInput.readUTFArray()`
** `UTF` has been renamed as `String` for the following without deprecation:
*** `GenericRecord.readUTF()`
*** `GenericRecord.readUTFArray()`
*** `GenericRecordBuilder.writeUTF()`
*** `GenericRecordBuilder.writeUTFArray()`
+
https://github.com/hazelcast/hazelcast/pull/18100[#18100]
* Per-entry statistics of maps now are disabled by default; they were enabled in
the previous releases. See the <<enh-42, Enhancements>> section below.
* The default value for cluster connection timeout for clients has been set as `-1` (infinite timeout):
This is the timeout value for the client to give up to connect to the current cluster.
For the default value, the client will not stop trying to connect to the target cluster.
See https://docs.hazelcast.com/imdg/4.2/clients/java.html#configuring-client-connection-retry[here]
for more information.
https://github.com/hazelcast/hazelcast/pull/18094[#18094]

[[enh-42]]
=== Enhancements

*_Hazelcast IMDG Open Source Enhancements:_*

* **Per-Entry Statistics of Maps:** Introduced a configuration option (`per-entry-stats-enabled`)
for retrieving per-entry statistics of a map, which is disabled by default.
See the https://docs.hazelcast.com/imdg/4.2/data-structures/map.html#accessing-entry-statistics[Accessing Map and Entry statistics section].
* **Default Serializer Overriding:** Added the ability to override Hazelcast's built-in serializers.
Also added the serialization support of `java.util.Optional`.
See the https://docs.hazelcast.com/imdg/4.2/serialization/serialization.html[Serialization chapter].

The following are the improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Added support of named parameters in SQL's `HazelcastFunction`.
https://github.com/hazelcast/hazelcast/pull/18328[#18328]
* Added the HTTPS/TLS support for phone home pings. Also enhanced the phone home data
by adding the following information:
** Java classpath on which the member runs
** Detailed client information such as total connection durations and client versions
** Total number of created proxies for each distributed object service
+
https://github.com/hazelcast/hazelcast/pull/18337[#18337],
https://github.com/hazelcast/hazelcast/pull/18326[#18326],
https://github.com/hazelcast/hazelcast/pull/18307[#18307],
https://github.com/hazelcast/hazelcast/pull/18287[#18287]
* Improved the `LIKE` query predicate so that it now supports indexes.
https://github.com/hazelcast/hazelcast/pull/18289[#18289]
* Added `management-permission` to the client permissions that defines which
Management Center client principals/endpoints are allowed to perform management tasks.
https://github.com/hazelcast/hazelcast/pull/18264[#18264]
* Added the temporal types support for indexes by introducing converters
for the missing types (`LocalTime`, `LocalDate`, `LocalDateTime` and `OffsetDateTime`)
https://github.com/hazelcast/hazelcast/pull/18244[#18244]
* Added the support of bitmap index statistics to be propagated to local
map statistics.
https://github.com/hazelcast/hazelcast/pull/18220[#18220]
* Improved the map store configuration such that it is enabled unless
you explicitly disable it; this improvement has been introduced to eliminate
the inconsistencies between map store's declarative and programmatic
configurations.
https://github.com/hazelcast/hazelcast/pull/18217[#18217]
* Implemented the High-Density Metadata Store to store all the metadata
for on-heap and off-heap storages. This new store is based on `BinaryElasticHashMap`.
A new type of record called `HDMetadataRecord` has been introduced for
this purpose that references the key and value part of the metadata.
https://github.com/hazelcast/hazelcast/pull/18186[#18186]
* Added the ability to register the class definition of the parent generic record
and check the class definition compatibility for nested portable fields.
https://github.com/hazelcast/hazelcast/pull/18180[#18180]
* Improved the SQL engine so that it attempts to re-use the already deserialized
values stored in an index; this has been improved the map scan operations
performance when there is at least one index on an IMap.
https://github.com/hazelcast/hazelcast/pull/18172[#18172]
* Added the `iterator()` and `iterable()` methods with different parameter
combinations to the map.
https://github.com/hazelcast/hazelcast/pull/18126[#18126]
* Added the support of non-nullable columns for the SQL service.
https://github.com/hazelcast/hazelcast/pull/18114[#18114]
* Implemented the fetch and offset SQL clauses without
pushing the operator on the individual member.
https://github.com/hazelcast/hazelcast/pull/18091[#18091]
* Introduced a new serialization mechanism for SQL row data. Previously, every value
was being serialized as `Data` which was inefficient and the non-Java clients could not
read some types, e.g., `decimal`. With this new mechanism, a new custom codec `SqlPageCodec`
has been introduced that serializes values using a custom built-in list serializer
depending on the type of the column.
https://github.com/hazelcast/hazelcast/pull/18089[#18089]
* Added `Nonnull` annotations to `StreamSerializer`.
https://github.com/hazelcast/hazelcast/pull/18071[#18071]
* Added the ability to cancel queries on the client side when there are active requests sent to
the member; this enhancement facilitates the future implementation of a non-blocking
SQL client handler.
https://github.com/hazelcast/hazelcast/pull/18047[#18047]
* Added the support of `OBJECT` type in the comparison operators in Hazelcast's SQL service.
https://github.com/hazelcast/hazelcast/pull/18016[#18016]
* Implemented the `ORDER BY` clause for the SQL service; it supports
the ASC and DESC sortings with limitations.
https://github.com/hazelcast/hazelcast/pull/18013[#18013]
* Added the support of `remainder` operation for Hazelcast's SQL service.
https://github.com/hazelcast/hazelcast/pull/17997[#17997]
* Added the support of `NOT LIKE` expression to Hazelcast's SQL service.
https://github.com/hazelcast/hazelcast/pull/17996[#17996]
* Introduced a new SQL threading model to improve its performance.
https://github.com/hazelcast/hazelcast/pull/17985[#17985]
* Introduced the support of schemas for the SQL public API.
https://github.com/hazelcast/hazelcast/pull/17953[#17953]
* Implemented the `IMap.entrySet()` method for the partition ID set.
https://github.com/hazelcast/hazelcast/pull/17937[#17937]
* Improved the discovery by external smart clients in the cloud environments:
the clients now only need to know the address of any member (or that of a load balancer
if members are exposed via load balancer).
https://github.com/hazelcast/hazelcast/pull/17895[#17895]
* Introduced a configuration property to ignore errors during enabling the
XXE protection. This protection works with JAXP 1.5 (Java 7 Update 40) and newer.
When an older JAXP implementation is added to the classpath, e.g., Xerces and Xalan,
an exception is thrown. The newly introduced property, namely `hazelcast.ignoreXxeProtectionFailures`,
allows you to ignore those exceptions.
https://github.com/hazelcast/hazelcast/issues/17839[#17839]
* Added the missing `replicatedmap-permission` support to the XML and YAML
configuration handlers.
https://github.com/hazelcast/hazelcast/pull/17810[#17810]
* Replaced `Charset` with `StandardCharsets` to be used in JSON querying.
https://github.com/hazelcast/hazelcast/pull/17741[#17741]
* Implemented migration listener for the Java client.
https://github.com/hazelcast/hazelcast/pull/17713[#17713]
* Introduced tenant control when creating JCache caches.
https://github.com/hazelcast/hazelcast/pull/17673[#17673]
* Added the `BigDecimal`,`LocalTime`,`LocalDate`,`LocalDateTime`,`OffsetDateTime` types to the Portable Serialization.
https://github.com/hazelcast/hazelcast/pull/17257[#17257]
* Introduced the `unparkAll()` method for event journal read operations.
https://github.com/hazelcast/hazelcast/pull/14081[#14081]

[[fixes-42]]
=== Fixes

* Fixed a regression issue where the locked and expired entry keys could not be
reached over indexes.
https://github.com/hazelcast/hazelcast/pull/18386[#18386]
* Improved the deserialization for indexes: when having multiple indexes on a map,
each time an entry is put in the map and thus to the index, the entry is
deserialized for each index instead just once. This was causing performance issues.
https://github.com/hazelcast/hazelcast/pull/18343[#18343]
* Fixed an issue where SQL's `ORDER BY` statement was failing if the field is indexed
and there are other clauses such as `WHERE` in the query.
https://github.com/hazelcast/hazelcast/pull/18341[#18341]
* Fixed an issue where `GenericRecord` could not be queried when the
in-memory format of the map is `OBJECT`.
https://github.com/hazelcast/hazelcast/issues/18336[#18336]
* Fixed a discrepancy between the behaviors of index-scan and full-scan in maps; the
eviction of the idle map entries was not stable in IMDG 4.x series due to this
discrepancy. 
https://github.com/hazelcast/hazelcast/pull/18334[#18334]
* Fixed an issue where the health monitor was logging no values for
garbage collection metrics.
https://github.com/hazelcast/hazelcast/pull/18317[#18317]
* Fixed an issue that occurred when there is Near Cache configured for both the member and
client sides for the same map and `serialize-keys` option is `false`.
https://github.com/hazelcast/hazelcast/pull/18312[#18312]
* Fixed an issue where the transactions was not throwing `TransactionTimeOutException`
in case of a timeout.
https://github.com/hazelcast/hazelcast/pull/18305[#18305]
* Fixed an issue where Hazelcast IMDG was not picking the `hazelcast.xml`
configuration file from the download package but from the current working
directory where IMDG has been started.
https://github.com/hazelcast/hazelcast/pull/18304[#18304]
* Fixed the race condition occurring during the serialization of writes for the
copy-on-write data structures.
https://github.com/hazelcast/hazelcast/pull/18285[#18285]
* Fixed an issue where the clients, in a blue/green deployment,
were hanging while reconnecting to the alternative cluster due to
mishandling of member list.
https://github.com/hazelcast/hazelcast/pull/18276[#18276]
* Fixed an issue where `CachedQueryEntry` could not be serialized since it didn't
have a default serializer.
https://github.com/hazelcast/hazelcast/pull/18238[#18238]
* Fixed an issue where the Java client was not receiving membership events
in its membership listener when a member with Hot Restart Persistence enabled is restarted.
https://github.com/hazelcast/hazelcast/issues/18234[#18234]
* Fixed a regression issue: when overlapping wildcard configurations
are defined declaratively, the most specific one was inheriting
attributes from the more generic one during parsing.
https://github.com/hazelcast/hazelcast/pull/18187[#18187]
* Fixed an issue where the non-UTF characters in a JSON value was
causing query failures.
https://github.com/hazelcast/hazelcast/pull/18183[#18183]
* Fixed an issue where tasks were not running in parallel when
they are submitted to all the cluster members in some scenarios.
https://github.com/hazelcast/hazelcast/pull/18107[#18107]
* Fixed an issue that prohibited Hazelcast from being used as Tomcat session manager
when it is also deployed in a web application context:
When a client application that uses Hazelcast tries to connect to the Hazelcast cluster and this
application's web sessions are persisted using Hazelcast's Tomcat session manager,
the session manager could not connect to the cluster. This has been
fixed by improving Hazelcast's service loader mechanism.
https://github.com/hazelcast/hazelcast/pull/18103[#18103]
* When the in-memory format of a map is NATIVE and the uploaded user code has missing 
classes (in case the user code deployment feature is used), the resulting exception
could not be seen on the client side when a map query is run. This was causing the
client to hang indefinitely and fixed by improving the failure handling for this case.
https://github.com/hazelcast/hazelcast/pull/18081[#18081]
* Fixed an issue where the queue items were being delivered more than once
when they are reproduced after a member leaves the cluster.
https://github.com/hazelcast/hazelcast/issues/18057[#18057]
* Fixed the syntax for `inMemoryFormat` variable in the `MapConfig.toString()` method.
https://github.com/hazelcast/hazelcast/pull/17976[#17976]
* Fixed a failure which happened when a client is recreated with the same
client failover configuration after creating a map that has the default near cache eviction
configuration.
https://github.com/hazelcast/hazelcast/issues/17952[#17952]
* Fixed several issues when handling the SQL expressions. The fixes
include not relying on Apache Calcite for inference and coercion anymore and
introducing custom operand checker implementations provided by every operator.
https://github.com/hazelcast/hazelcast/pull/17947[#17947]
* Fixed an issue where the metrics for map hits statistics in Management Center
were decreasing as the map entries are being expired.
https://github.com/hazelcast/hazelcast/issues/17930[#17930]
* Fixed an issue where the clients were opening two connections
to the same member when the member is behind a private network.
https://github.com/hazelcast/hazelcast/pull/17844[#17844]
* Fixed an issue where the failures in `SessionAwareSemaphore` was preventing
the acquired permits from their releases.
https://github.com/hazelcast/hazelcast/pull/17826[#17826]
* Fixed an issue where the Javadoc of release methods for
session-aware semaphore structure was incorrectly addressing
"threads" instead of "Hazelcast instances".
https://github.com/hazelcast/hazelcast/pull/17823[#17823]
* Fixed an issue where the `remove()` and `delete()` operations
of maps were not updating the local map statistics.
https://github.com/hazelcast/hazelcast/pull/17771[#17771]
* Fixed the metrics unit for cache statistics to be declared in
microseconds.
https://github.com/hazelcast/hazelcast/pull/17742[#17742]
* Fixed a failure when retrieving the member state before the member becomes ACTIVE
on Kubernetes using Helm charts.
https://github.com/hazelcast/hazelcast/pull/17773[#17773]
* Fixed an issue where the parsing of configurations for some Hazelcast features, such as 
Hot Restart and user code deployment, was
overriding the existing configuration values.
https://github.com/hazelcast/hazelcast/pull/18036[#18036],
https://github.com/hazelcast/hazelcast/pull/18034[#18034],
https://github.com/hazelcast/hazelcast/pull/17675[#17675],
https://github.com/hazelcast/hazelcast/pull/17681[#17681],
https://github.com/hazelcast/hazelcast/pull/17885[#17885],
https://github.com/hazelcast/hazelcast/pull/17917[#17917],
https://github.com/hazelcast/hazelcast/pull/17923[#17923],
https://github.com/hazelcast/hazelcast/pull/17924[#17924],
https://github.com/hazelcast/hazelcast/pull/17940[#17940],
https://github.com/hazelcast/hazelcast/pull/17945[#17945],
https://github.com/hazelcast/hazelcast/pull/17946[#17946],
https://github.com/hazelcast/hazelcast/pull/17875[#17875],
https://github.com/hazelcast/hazelcast/pull/17878[#17878],
https://github.com/hazelcast/hazelcast/pull/17969[#17969],
https://github.com/hazelcast/hazelcast/pull/17971[#17971],
https://github.com/hazelcast/hazelcast/pull/17972[#17972]
* Removed `InetSocketAddressCache` from the Java client code
so that the client can continue to work, while preserving the
behaviors in a Blue/Green Deployment scenario; the Java client was not able
to resolve the new address of a restarted member, e.g., for a setup in Docker environment.
https://github.com/hazelcast/hazelcast/pull/17239[#17239] 

[[rd-42]]
=== Removed/Deprecated Features

* The Symmetric Encryption feature has been deprecated. You can
use the TLS/SSL protocol to establish an encrypted communication
across your Hazelcast cluster.
* The following system properties have been deprecated:
** `hazelcast.partition.group.rack`
** `hazelcast.partition.group.host`
** `hazelcast.hotrestart.free.native.memory.percentage`

[[contributors-42]]
===  Contributors

We would like to thank the contributors from our open source
community who worked on this release:

* https://github.com/lprimak[Lenny Primak]
* https://github.com/petprog[Farinu Taiwo]
* https://github.com/abdullahcevik[Abdullah Cevik]
* https://github.com/peterjot[Piotr Jasina]
* https://github.com/zalintyre[Franz Wimmer]
* https://github.com/sgflt[Lukáš Kvídera]
* https://github.com/alekseybeliyb[Aleksey Kaurov]
* https://github.com/aaronriekenberg[Aaron Riekenberg]
* https://github.com/TomaszGaweda[Tomasz Gaweda]

